export const footerData = {
    business: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing',
        socialLinks: [
            { href: '#', iconClass: 'bi bi-facebook' },
            { href: '#', iconClass: 'bi bi-twitter-x' },
            { href: '#', iconClass: 'bi bi-instagram' },
        ],
        explore: [
            { text: 'About us', href: '#' },
            { text: 'Services', href: '#' },
            { text: 'Clients', href: '#' },
            { text: 'Pricing', href: '#' },
        ],
        useful: [
            { text: 'Contact', href: '#' },
            { text: 'FAQs', href: '#' },
            { text: 'Careers', href: '#' },
            { text: 'Policy', href: '#' },
        ],
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'Help Center', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    corporate: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing',
        socialLinks: [
            { href: '#', iconClass: 'bi bi-facebook' },
            { href: '#', iconClass: 'bi bi-twitter-x' },
            { href: '#', iconClass: 'bi bi-instagram' },
        ],
        explore: [
            { text: 'About us', href: '#' },
            { text: 'Services', href: '#' },
            { text: 'Clients', href: '#' },
            { text: 'Pricing', href: '#' },
        ],
        useful: [
            { text: 'Contact', href: '#' },
            { text: 'FAQs', href: '#' },
            { text: 'Careers', href: '#' },
            { text: 'Policy', href: '#' },
        ],
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'Help Center', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    creativeAgency: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo sit facilis cum nisi magnam',
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    interior: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo sit facilis cum nisi magnam',
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    marketing: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo sit facilis cum nisi magnam',
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    mediaAgency: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo sit facilis cum nisi magnam',
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    portfolioFullWidth: {
        rights: "FlaTheme",
        links: [
            { text: 'About us', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    portfolioGrid: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo sit facilis cum nisi magnam',
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    portfolioVertical: {
        rights: "FlaTheme",
        socialLinks: [
            { href: '#', iconClass: 'bi bi-facebook' },
            { href: '#', iconClass: 'bi bi-twitter-x' },
            { href: '#', iconClass: 'bi bi-instagram' },
        ],
    },
    startup: {
        logoText: 'Logo',
        about: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo sit facilis cum nisi magnam',
        email: "contact@example.com",
        emailInfo: "Mon-Fri 9am-5pm",
        phone: "+123 456 7890",
        phoneInfo: "Call or WhatsApp",
        rights: "FlaTheme, All Rights Reserved.",
        helpItems: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
    portfolio: {
        rights: "FlaTheme, All Rights Reserved",
        links: [
            { text: 'About us', href: '#' },
            { text: 'FAQ', href: '#' },
            { text: 'Contact', href: '#' },
        ],
    },
};
